# .github/workflows/prd-deployment.yml
name: Production Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' # Matches tags like v1.2.3
  workflow_dispatch: {}

jobs:
  build-static-assets:
    name: âš™ï¸ Build Gatsby Static Assets
    runs-on: ubuntu-latest
    environment:
      name: prd
    env:
      DEPLOY_ENV: prd

    steps:
      - name: ğŸ“„ Checkout Repository
        uses: actions/checkout@v4

      - name: âš™ï¸ Detect Package Manager
        id: detect-pm
        run: |
          if [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
          elif [ -f "package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
          else
            echo "Unable to detect package manager"
            exit 1
          fi

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-pm.outputs.manager }}

      - name: â¬‡ï¸ Restore Gatsby Cache
        uses: actions/cache@v4
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-${{ hashFiles('**/yarn.lock', '**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-

      - name: ğŸ“¦ Install Dependencies
        run: ${{ steps.detect-pm.outputs.manager }} ${{ steps.detect-pm.outputs.command }}

      - name: âš™ï¸ Build with Gatsby
        env:
          PREFIX_PATHS: "true"
        run: ${{ steps.detect-pm.outputs.manager }} run build

      - name: ğŸ“¤ Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: prd-build-artifact
          path: ./public

  terraform-deploy:
    name: âš™ï¸ Deploy AWS Infrastructure (Terraform)
    runs-on: ubuntu-latest
    environment:
      name: prd

    outputs:
      dest_bucket_name: ${{ steps.outputs.outputs.dest_bucket_name }}
      cloudfront_distribution_id: ${{ steps.outputs.outputs.cloudfront_distribution_id }}

    steps:
      - name: ğŸ“„ Checkout Repository (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: âš™ï¸ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: âš™ï¸ Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: âš™ï¸ Terraform Init
        working-directory: infra
        run: terraform init -input=false

      - name: âš™ï¸ Select/Create Terraform Workspace
        working-directory: infra
        run: terraform workspace select -or-create prd-web

      - name: âš™ï¸ Terraform Plan
        working-directory: infra
        run: terraform plan --var-file=config/prd.tfvars -out=output.tfplan -input=false

      - name: âš™ï¸ Terraform Apply
        working-directory: infra
        run: terraform apply -input=false --auto-approve output.tfplan

      - name: âš™ï¸ Export Terraform Output (Bucket Name)
        id: outputs
        working-directory: infra
        run: |
          echo "dest_bucket_name=$(terraform output -raw origin_bucket_name)" >> $GITHUB_OUTPUT
          echo "cloudfront_distribution_id=$(terraform output -raw cloudfront_distribution_id)" >> $GITHUB_OUTPUT

  deploy-to-s3:
    name: ğŸš€ Deploy to S3 Bucket
    runs-on: ubuntu-latest
    needs: [build-static-assets, terraform-deploy]
    environment:
      name: prd

    steps:
      - name: â¬‡ï¸ Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: prd-build-artifact
          path: public

      - name: âš™ï¸ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: ğŸš€ Sync Static Assets to S3
        run: aws s3 sync --delete public s3://${{ needs.terraform-deploy.outputs.dest_bucket_name }}

      - name: ğŸš€ Invalidate Cloudfront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ needs.terraform-deploy.outputs.cloudfront_distribution_id }} --paths "/*"